apiVersion: v1
kind: Pod
metadata:
  name: pod-privileged
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginxinc/nginx-unprivileged
      securityContext:
        privileged: true