apiVersion: v1
kind: Pod
metadata:
  name: 02-hostpath-pod
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginxinc/nginx-unprivileged
      volumeMounts:
        - mountPath: /foo
          name: example-volume
          readOnly: true
  volumes:
    - name: example-volume
      hostPath:
        path: /home/valhalla/architecture-pro-propdevelopment/Task7